### ISSUE TITLE
getting unexpected error on registering the mobile number to signal

### ISSUE THREAD

**Issue by aleeshanoushad** [lwesterhof/semaphore#32]
when i try to register phone number in signal using this **{"type": "register", "username": "+91813XXXXXX9"}** , i am getting **{"type":"unexpected_error","data":{"msg_number":0,"error":true,"request":{"type":"register","username":"+91813XXXXXX9","expiresInSeconds":0,"when":0,"version":"v0"}}}**

i am new to this ,please help.

**Comment by S7R1D3R** [comment]
Hello mate, I was new some days ago as well and I understand the frustration. I will leave here some documentation from westerhof and some of my own that I find it quite useful. Remember that if you are already registered with your phone number you want to do {"type": "link", "deviceName": "NameOfDeviceAsYouWish"} instead of register. Hope this helps you

`# Installation / Setup

## Signald and Semaphore

1. Install signald or build from source

    $ git clone https://gitlab.com/thefinn93/signald.git
    $ cd signald
    $ make installDist
    $ make setup

2. Install Semaphore

    $ pip install semaphore-bot

- QUICKSTART

1. Start signald
    $ cd signald
    $ build/install/signald/bin/signald

2. Open a new terminal and connect to signald control socket
    $ nc -U /var/run/signald/signald.sock

A1. Register phone number with Signal by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number)
    $ {"type": "register", "username": "+xxxxxxxxxxx"}

A2. Verify phone number with SMS verification code by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number and zzz-zzz with verification code)
    $ {"type": "verify", "username": "+xxxxxxxxxxx", "code": "zzz-zzz"}

A3. Subscribe to receive messages for the bot by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number)
    $ {"type": "subscribe", "username": "+xxxxxxxxxxx"}

A4. Open a new terminal and set the SIGNAL_PHONE_NUMBER environment variable to your phone number
    $ export SIGNAL_PHONE_NUMBER=+xxxxxxxxxxx

B1. Once connected, issue the link command by entering the following into netcat and pressing enter
    $ {"type": "link", "deviceName": "your-device-name"}

B2. After a little wait you should receive a notice in the following format:
    $ {"type":"linking_uri","data":{"uri":"tsdevice:/?uuid=aes8EW8nC14Xz0aV-qugFw&pub_key=BQFy%2FyfItwo4LD3wqY7LV6i4nkWIqtYA6%2BpmlnnCk7As"}}

B3. Copy the returned uri (the double quoted string staring with 'tsdevice'), and use qrencode to output a qr code in the terminal with
    $ qrencode -t ANSI "tsdevice:/?uuid=aes8EW8nC14Xz0aV-qugFw&pub_key=BQFy%2FyfItwo4LD3wqY7LV6i4nkWIqtYA6%2BpmlnnCk7As`

**Comment by S7R1D3R** [comment]
Hello mate, I was new some days ago as well and I understand the frustration. I will leave here some documentation from westerhof and some of my own that I find it quite useful. Remember that if you are already registered with your phone number you want to do {"type": "link", "deviceName": "NameOfDeviceAsYouWish"} instead of register. Hope this helps you

`# Installation / Setup

## Signald and Semaphore

1. Install signald or build from source

    $ git clone https://gitlab.com/thefinn93/signald.git
    $ cd signald
    $ make installDist
    $ make setup

2. Install Semaphore

    $ pip install semaphore-bot

- QUICKSTART

1. Start signald
    $ cd signald
    $ build/install/signald/bin/signald

2. Open a new terminal and connect to signald control socket
    $ nc -U /var/run/signald/signald.sock

A1. Register phone number with Signal by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number)
    $ {"type": "register", "username": "+xxxxxxxxxxx"}

A2. Verify phone number with SMS verification code by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number and zzz-zzz with verification code)
    $ {"type": "verify", "username": "+xxxxxxxxxxx", "code": "zzz-zzz"}

A3. Subscribe to receive messages for the bot by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number)
    $ {"type": "subscribe", "username": "+xxxxxxxxxxx"}

A4. Open a new terminal and set the SIGNAL_PHONE_NUMBER environment variable to your phone number
    $ export SIGNAL_PHONE_NUMBER=+xxxxxxxxxxx

B1. Once connected, issue the link command by entering the following into netcat and pressing enter
    $ {"type": "link", "deviceName": "your-device-name"}

B2. After a little wait you should receive a notice in the following format:
    $ {"type":"linking_uri","data":{"uri":"tsdevice:/?uuid=aes8EW8nC14Xz0aV-qugFw&pub_key=BQFy%2FyfItwo4LD3wqY7LV6i4nkWIqtYA6%2BpmlnnCk7As"}}

B3. Copy the returned uri (the double quoted string staring with 'tsdevice'), and use qrencode to output a qr code in the terminal with
    $ qrencode -t ANSI "tsdevice:/?uuid=aes8EW8nC14Xz0aV-qugFw&pub_key=BQFy%2FyfItwo4LD3wqY7LV6i4nkWIqtYA6%2BpmlnnCk7As`

**Comment by S7R1D3R** [comment]
Hello mate, I was new some days ago as well and I understand the frustration. I will leave here some documentation from westerhof and some of my own that I find it quite useful. Remember that if you are already registered with your phone number you want to do {"type": "link", "deviceName": "NameOfDeviceAsYouWish"} instead of register. Hope this helps you

# Installation / Setup

## Signald and Semaphore

1. Install signald or build from source

    $ git clone https://gitlab.com/thefinn93/signald.git
    $ cd signald
    $ make installDist
    $ make setup

2. Install Semaphore

    $ pip install semaphore-bot

- QUICKSTART

1. Start signald
    $ cd signald
    $ build/install/signald/bin/signald

2. Open a new terminal and connect to signald control socket
    $ nc -U /var/run/signald/signald.sock

A1. Register phone number with Signal by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number)
    $ {"type": "register", "username": "+xxxxxxxxxxx"}

A2. Verify phone number with SMS verification code by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number and zzz-zzz with verification code)
    $ {"type": "verify", "username": "+xxxxxxxxxxx", "code": "zzz-zzz"}

A3. Subscribe to receive messages for the bot by sending following message on the control socket (replace +xxxxxxxxxxx with bot Signal number)
    $ {"type": "subscribe", "username": "+xxxxxxxxxxx"}

A4. Open a new terminal and set the SIGNAL_PHONE_NUMBER environment variable to your phone number
    $ export SIGNAL_PHONE_NUMBER=+xxxxxxxxxxx

B1. Once connected, issue the link command by entering the following into netcat and pressing enter
    $ {"type": "link", "deviceName": "your-device-name"}

B2. After a little wait you should receive a notice in the following format:
    $ {"type":"linking_uri","data":{"uri":"tsdevice:/?uuid=aes8EW8nC14Xz0aV-qugFw&pub_key=BQFy%2FyfItwo4LD3wqY7LV6i4nkWIqtYA6%2BpmlnnCk7As"}}

B3. Copy the returned uri (the double quoted string staring with 'tsdevice'), and use qrencode to output a qr code in the terminal with
    $ qrencode -t ANSI "tsdevice:/?uuid=aes8EW8nC14Xz0aV-qugFw&pub_key=BQFy%2FyfItwo4LD3wqY7LV6i4nkWIqtYA6%2BpmlnnCk7As

**Comment by aleeshanoushad** [comment]
Hai Joaquim Teixeira Duarte

i am also refering the same doc, but i am getting error in step first, which is registering the number in signal.

on registering i am getting
{"type": "register", "username": "+91XXXXXXXXX9"}
{"type":"unexpected_error","data":{"msg_number":0,"error":true,"request":{"type":"register","username":"+91XXXXXXXXX9","expiresInSeconds":0,"when":0,"version":"v0"}}}

In the socket handler i m getting this error.
ERROR io.finn.signald.SocketHandler - Catching
org.whispersystems.signalservice.api.push.exceptions.CaptchaRequiredException: null
	at org.whispersystems.signalservice.internal.push.PushServiceSocket$1.handle(PushServiceSocket.java:267) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
	
	please help me with this.its being a month now

**Comment by lwesterhof** [comment]
This is not a Semaphore issue, you can't register because you need to fill in a captcha. See https://gitlab.com/signald/signald/-/wikis/Captchas

**Comment by aleeshanoushad** [comment]
Thanks alot for the response. 
but i have a blank page in this page..https://signalcaptchas.org/registration/generate.html  if you know how to create captcha. please help me

**Comment by lwesterhof** [comment]
Maybe access to Google services is blocked/censored at your location?

**Comment by thefinn93** [comment]
@aleeshanoushad try a private browsing window. That's what was required in [this issue](https://gitlab.com/signald/signald/-/issues/132) where someone was also unable to see the captcha

**Comment by aleeshanoushad** [comment]
@thefinn93 Thanks for the replay.it help me to create the captcha but after registering using captcha i am getting error.

{"id":"","type":"unexpected_error","data":{"msg_number":0,"message":"Cannot construct instance of `io.finn.signald.JsonRequest` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('type')\n at [Source: UNKNOWN; line: -1, column: -1]","error":true}}

Anybody have any idea about this error.. please help.

**Comment by thefinn93** [comment]
That looks like a JSON error. I'd need to see the request you're making to get that. It may be easier to download [signaldctl](https://gitlab.com/signald/signald-go/-/blob/main/cmd/signaldctl/README.md) and run `signaldctl account register --captcha <captcha token> <phone number>`, which will handle all the JSON stuff for you.
